title: Go4Go
description: Go notes - updating constantly.
# Theme settings
remote_theme: pages-themes/midnight@v0.2.0

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag


author: Theresa Yip
email: ymy.theresa@gmail.com

Social media links:
github_username:  ymytheresa

# Exclude files from being included in the site:
show_downloads: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
