title: Go4Go
description: Go notes - updating constantly.
author: Theresa Yip
email: ymy.theresa@gmail.com

# Theme settings
remote_theme: pages-themes/midnight@v0.2.0

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Social media links
github_username: ymytheresa

# Custom collection for your markdown assets
collections:
  notes:
    output: true
    permalink: /:collection/:name

# Default layout for collection items
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "page"

# Site settings
show_downloads: true

# Exclude assets from being included in the site:
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional: If you want to use a custom domain
# url: "http://yourdomain.com"
# baseurl: ""
